name: virgo
description: "An AI app for promoting economic empowerment & leadership for women and girls"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.4.5
  file_picker: ^8.1.3
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  http: ^1.2.2
  pdfx: ^2.8.0
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
